import type { NextPage } from "next";
import { useEffect, useRef, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.scss";
import Logo from "../images/svgUndraw.svg";
import { BiHappy, BiChevronRight } from "react-icons/bi";
import { MdOutlineEmail } from "react-icons/md";
import {
  BsLinkedin,
  BsTelephone,
  BsCode,
  BsPhone,
  BsDot,
} from "react-icons/bs";
import {
  SiNextdotjs,
  SiReact,
  SiJavascript,
  SiTypescript,
  SiNodedotjs,
  SiGithub,
} from "react-icons/si";

const Home: NextPage = () => {
  const [handleDock, setHandleDock] = useState(false);
  const [pageSize, setPageSize] = useState(0);

  const header = useRef(null);
  const aboutMe = useRef(null);
  const projects = useRef(null);
  const services = useRef(null);
  const skills = useRef(null);

  const scrollToComponent = (ref: any) => {
    ref.current.scrollIntoView({ behavior: "smooth" });
  };

  const handleShowDock = () => {
    setHandleDock(!handleDock);
  };

  useEffect(() => {
    if (pageSize === window.innerWidth) return;
    setPageSize(window.innerWidth);
  }, []);

  return (
    <div>
      <Head>
        <title>Guilherme Bersi | @devbersi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className={styles.sideDock}>
        <div
          className={styles.icons}
          style={{
            display: handleDock ? "flex" : "none",
          }}
        >
          <BsDot
            style={{
              fontSize: "20px",
              color: "#fff",
              WebkitAnimation: "glow 1s ease-in-out infinite alternate",
              MozAnimation: "glow 1s ease-in-out infinite alternate",
              animation: "glow 1s ease-in-out infinite alternate",
              cursor: "pointer",
            }}
            onClick={() => scrollToComponent(header)}
            title="Home"
          />
          <BsDot
            style={{
              fontSize: "20px",
              color: "#fff",
              WebkitAnimation: "glow 1s ease-in-out infinite alternate",
              MozAnimation: "glow 1s ease-in-out infinite alternate",
              animation: "glow 1s ease-in-out infinite alternate",
              cursor: "pointer",
            }}
            onClick={() => scrollToComponent(aboutMe)}
            title="About Me"
          />
          <BsDot
            style={{
              fontSize: "20px",
              color: "#fff",
              WebkitAnimation: "glow 1s ease-in-out infinite alternate",
              MozAnimation: "glow 1s ease-in-out infinite alternate",
              animation: "glow 1s ease-in-out infinite alternate",
              cursor: "pointer",
            }}
            onClick={() => scrollToComponent(projects)}
            title="Projects"
          />
          <BsDot
            style={{
              fontSize: "20px",
              color: "#fff",
              WebkitAnimation: "glow 1s ease-in-out infinite alternate",
              MozAnimation: "glow 1s ease-in-out infinite alternate",
              animation: "glow 1s ease-in-out infinite alternate",
              cursor: "pointer",
            }}
            onClick={() => scrollToComponent(services)}
            title="Services"
          />
          <BsDot
            style={{
              fontSize: "20px",
              color: "#fff",
              WebkitAnimation: "glow 1s ease-in-out infinite alternate",
              MozAnimation: "glow 1s ease-in-out infinite alternate",
              animation: "glow 1s ease-in-out infinite alternate",
              cursor: "pointer",
            }}
            onClick={() => scrollToComponent(skills)}
            title="Skills"
          />
        </div>
        <div className={styles.toggle}>
          <BiChevronRight
            size={30}
            style={{
              backgroundColor: "#4444",
              width: "43px",
              height: "15%",
              borderRadius: "25px",
              color: "#fff",
              cursor: "pointer",
            }}
            onClick={() => handleShowDock()}
          />
        </div>
      </div>
      <main className={styles.Main}>
        <div ref={header} className={styles.HeaderContainer}>
          <div className={styles.HeaderTitle}>
            <h2 onClick={() => scrollToComponent(header)}>devbersi</h2>
          </div>
          <ul className={styles.HeaderList}>
            <li>
              <a onClick={() => scrollToComponent(aboutMe)}>About Me</a>
            </li>
            <li onClick={() => scrollToComponent(projects)}>
              <a>Projects</a>
            </li>
            <li onClick={() => scrollToComponent(services)}>
              <a>Services</a>
            </li>
            <li onClick={() => scrollToComponent(skills)}>
              <a>My Skills</a>
            </li>
          </ul>
        </div>
        <div className={styles.ContentPage}>
          <div className={styles.Introduction}>
            <div className={styles.Infos}>
              <h1 className={styles.TextIntroduction}>
                Hello Folks, I'm Guilherme Bersi
              </h1>
              <div>
                <p className={styles.TextPosition}>
                  Fullstack Software Developer
                </p>
              </div>
            </div>
            <div className={styles.Buttons}>
              <a
                href="https://www.linkedin.com/in/guilherme-bersi-7696861b3/"
                target="_blank"
                className={styles.DownloadButton}
              >
                See my carreer
              </a>
              <button className={styles.ContactButton}>
                <a href="https://contate.me/devbersi" target="_blank">
                  Send me a Message
                </a>
              </button>
            </div>
          </div>
          <div className={styles.Illustration}>
            <Image src={Logo} />
          </div>
        </div>
        <div ref={aboutMe} className={styles.AboutMe}>
          <div className={styles.TextAboutMe}>
            <h4>About Me</h4>
            <p>
              I'm Guilherme Bersi i'm 22 years old and i'm Mid-Level Software
              Developer working with Javascript stack, my main tecnologies is
              React/NextJS, NodeJS and React Native and along my career i always
              used Typescript for development, I worked in a lot projects,
              personal projects, closed projects and etc...If you need me for
              something, don't worry, just send me a message and i will help you
              for anything
            </p>
          </div>
          <div className={styles.ListContacts}>
            <ul>
              <li>
                <div>
                  <BiHappy style={{ color: "#847feb" }} size={30} />
                </div>
                <h4>Meu Nome</h4>
                <p>Guilherme Bersi</p>
              </li>
              <li>
                <div>
                  <MdOutlineEmail style={{ color: "#847feb" }} size={30} />
                </div>
                <h4>E-mail</h4>
                <p>guibersi.13@outlook.com</p>
              </li>
              <li>
                <div>
                  <BsLinkedin style={{ color: "#847feb" }} size={30} />
                </div>
                <h4>LinkedIn</h4>
                <p>Guilherme Bersi</p>
              </li>
              <li>
                <div>
                  <BsTelephone style={{ color: "#847feb" }} size={30} />
                </div>
                <h4>Telefone</h4>
                <p>(15) 99700-8154</p>
              </li>
            </ul>
          </div>
        </div>
        <main ref={projects} className={styles.ProjectsPage}>
          <h4>Projects</h4>
          <div className={styles.GridProjects}>
            <div className={styles.FirstRow}>
              <div className={styles.Project}>
                <div className={styles.ImageProject}>
                  <h4>Private Project</h4>
                </div>
                <div className={styles.DescriptionProject}>
                  <p className={styles.TypeProject}>Project for company</p>
                  <p>Employee Management</p>
                  <span>
                    Tech: ReactJS, Typescript, ContextAPI, Styled Components and
                    Java Spring Boot.
                  </span>
                </div>
              </div>
              <div className={styles.Project}>
                <div className={styles.ImageProject}>
                  <h4>Private Project</h4>
                </div>
                <div className={styles.DescriptionProject}>
                  <p className={styles.TypeProject}>Project for company</p>
                  <p>Marketplace for Coffeeshop</p>
                  <span>
                    Tech: React Native, Typescript, Expo, NodeJS, MySQL.
                  </span>
                </div>
              </div>
              <div className={styles.Project}>
                <div className={styles.ImageProject}>
                  <h4>Private Project</h4>
                </div>
                <div className={styles.DescriptionProject}>
                  <p className={styles.TypeProject}>Project for company</p>
                  <p>Incident Report App</p>
                  <span>
                    Tech: React Native, Typescript, Styled-Components, Expo,
                    NodeJS, AdonisJS, MySQL.
                  </span>
                </div>
              </div>
            </div>
            <div className={styles.FirstRow}>
              <div className={styles.Project}>
                <div className={styles.ImageProject}>
                  <h4>Private Project</h4>
                </div>
                <div className={styles.DescriptionProject}>
                  <p className={styles.TypeProject}>Project for company</p>
                  <p>Applyer of tax</p>
                  <span>
                    Tech: ReactJS, Typescript, Styled-Components, NodeJS, MySQL.
                  </span>
                </div>
              </div>
              <div className={styles.Project}>
                <div className={styles.ImageProject}>
                  <h4>Private Project</h4>
                </div>
                <div className={styles.DescriptionProject}>
                  <p className={styles.TypeProject}>Project for company</p>
                  <p>Basic to-do/pomodoro Web</p>
                  <span>Tech: NextJS, Typescript, scss, </span>
                </div>
              </div>
              <div className={styles.Project}>
                <div className={styles.ImageProject}>
                  <h4>In Development</h4>
                </div>
                <div className={styles.DescriptionProject}>
                  <p className={styles.TypeProject}>In Development</p>
                  <p>Finance Manager</p>
                  <span>Tech: NextJS, Typescript, scss, NodeJS.</span>
                </div>
              </div>
            </div>
          </div>
        </main>
        <div ref={services} className={styles.ServicesPage}>
          <div className={styles.Services}>
            <h4>Services/Freelance</h4>
            <div className={styles.ServicesList}>
              <div className={styles.ServicesCard}>
                <BsCode size={62} style={{ color: "#6C63FF" }} />
                <p>
                  Site <br /> Builder
                </p>
              </div>
              <div className={styles.ServicesCard}>
                <BsCode size={62} style={{ color: "#6C63FF" }} />
                <p>
                  Site <br /> Maintence
                </p>
              </div>
              <div className={styles.ServicesCard}>
                <BsPhone size={62} style={{ color: "#6C63FF" }} />
                <p>
                  App <br /> Creator
                </p>
              </div>
            </div>
          </div>
          <div ref={skills} className={styles.Skills}>
            <h4>My Skills</h4>
            <div className={styles.SkillsList}>
              <div className={styles.SkillsCard}>
                <SiNextdotjs size={72} style={{ color: "#6C63FF" }} />
              </div>
              <div className={styles.SkillsCard}>
                <SiReact size={72} style={{ color: "#6C63FF" }} />
              </div>
              <div className={styles.SkillsCard}>
                <SiJavascript size={72} style={{ color: "#6C63FF" }} />
              </div>
              <div className={styles.SkillsCard}>
                <SiTypescript size={72} style={{ color: "#6C63FF" }} />
              </div>
              <div className={styles.SkillsCard}>
                <SiNodedotjs size={72} style={{ color: "#6C63FF" }} />
              </div>
              <div className={styles.SkillsCard}>
                <SiGithub size={72} style={{ color: "#6C63FF" }} />
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
